modLoader = "javafml"
loaderVersion = "[1.20,)"
license = "MIT"
[[mods]]
modId = "fathermob"
version = "1.0.0"
displayName = "FatherMob"
description = "A mod that replaces skeletons with apple-throwing skeletons."

[[dependencies.fathermob]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.6,)"

